[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"

[project]
name = "qt_precommit"
version = "0.0.1"

[project.scripts]
qt_precommit = "qt_precommit.cli:qt_precommit_cli"
